### ISSUE TITLE
Comments @minimize

### ISSUE THREAD

**Issue by evil-morfar** [Eriner/RCLootCouncil#11]
- Line 1113 - No biggie
    `EmptyTexture:Hide()`
should be moved under line 1109 to be:
```lua
if not isMinimized then
    CurrentItemTexture:Show(); -- Open up the icon box
    EmptyTexture:Hide(); -- Hide the empty texture
else
```
- The session buttons should be hidden as well on minimize - makes no sense having 6+ icons showing next to it. Easiest way I could think of:
```lua
@Line 2642
if lootTable[i] and not isMinimized then
```
Then adding a `RCLootCouncil_Mainframe:UpdateSessionButtons()` after `isMinimized = true/false` in `function RCLootCouncil_Mainframe.minimize(action)` makes it work.

- The minimize button is overlapping textures when two items are showed, making it hard to click. Making the button a bit smaller, and moving it closer to the edge is a nice fix:
```xml
@Line 649
<Button name="BtMinimize" inherits="UIPanelButtonTemplate"  text="-">
     <Size>
          <AbsDimension x="20" y="20" />
     </Size>
     <Anchors>
         <Anchor point="TOPRIGHT" relativePoint="TOPRIGHT" x="-5" y="-5"></Anchor>
     </Anchors>
     <Scripts>
         <OnClick>
             RCLootCouncil_Mainframe.minimizeBtOnClick();
         </OnClick>
      </Scripts>
</Button>
```
- Now that I think about it I should probably just have made a commit with the changes :P

**Comment by Eriner** [comment]
Yeah, I had the session buttons hidden originally, but I thought it may be best to leave them in as it shows you the items selected while it is minimized, but you're right of course.

I will implement these changes and push.

**Comment by evil-morfar** [comment]
Sounds good. I worked on the missing russian fonts, which I have a fix for, but can't test for obvious reasons. I'll push it to master.

**Comment by Eriner** [comment]
Yeah, I am unable to test the russian fonts as well, but I may try to change my system fonts and such (on a keybind to revert) to test. I believe the minimize code is working as intended; thanks for your fixes. I haven't heard any complaints about the cross-realm raiding, so I think I am going to push it to master with the rest of the fixes/additions. If we hear complaints, we can revert and fix again. I will do this tomorrow morning.

**Comment by evil-morfar** [comment]
Sounds good.
It should work though, as changing the font is hardcoded in the Blizz templates. All I did was removing the calls to specific fonts, and just let it inherit the Blizz templates.

**Comment by Eriner** [comment]
Great. Once WoW is back up (maintenance) I will verify that the merges locally function as intended, push to github, then upload zip to curseforge.

**Comment by Eriner** [comment]
Done, everything should be functional. Submitting new zip to CurseForge now.
