### ISSUE TITLE
Request: Make the Loot History better

### ISSUE THREAD

**Issue by Raylehnhoff** [Eriner/RCLootCouncil#19]
Depending on how much time you'd want to devote to this frame, I have several suggestions:

1. Add column sorting (similar to the main loot frame)
1. Make the Loot ordered by Date with an expandable field. Expanding the field would show all loot distributed under that eventType (date or player name, a good argument can be had for either). Rarity does something like this. This would allow me to see who got loot during a particular raid significantly quicker than the current setup.
1. If a player was looted current (Tier 17) tokens, it would be incredibly helpful to have this information readily available on the loot history. Displaying this information upon clicking a player's name is one possibility:
    1. "Daegan has received 3 tokens: Heroic Helm, Heroic Chest, Heroic Gloves"

I'm trying to pick up Lua and the RCLC code base, but I'm a C# web developer by trade. It's quite a bit different from what I'm used to.

**Comment by evil-morfar** [comment]
The loot history will be revised for a future update (actually the whole addon is).

1. Should of course be there.
2. Expanding fields aren't really an option as such, as it's really hard/inefficient to make (will either look weird or require a lot of extra windows). Thoughts below.
3. Haven't thought about that, but it makes sense.

I'm thinking something like having two tables; a smaller one for filtering, and one for actual data. The filter table would then show some toggable "presets" like date, raid, playername - and clicking a filter would display any data with that "tag".

**Comment by Raylehnhoff** [comment]
The issue with that approach is that it doesn't make the data much more readable than it currently is.

Let me present a use case:

A player raided with us last week. Since last week, he has left the guild, and we wanted to do a check to see what we looted him. In the above use-case, I'd sort by the date "tag", scroll through to find the date in question, and then scroll through to find the players name.

It would be incredibly time consuming, and would have a lot of information in the window that I don't even care about. 

Now, using something similar to rarity's collapseable grouping, we'd have:

````
[-] 2/12/2015 - Blackrock Foundry Heroic
 |- [-] Daegan
 |------[Cool Epic] DE
 |------[Cool Epic] Main Spec
 |- [+] Notdaegan
 |- [+] Notdaegan2
[+] 2/14/2015 - Blackrock Foundry Heroic
[+] 2/17/2015 - Blackrock Foundry Mythic
````

Which I think we can agree would show the information I would want in a rapid drill-down. This is operating on the assumption that doing a double-grouped drilldown would be possible. Having coded things like this myself, I'm well aware that it's not easy, but whether a feature is easy to implement or not shouldn't be cause for implementing it. The hard features set us apart from the crowd :) 

Doing this would eliminate the need for sorting and ordering as well, since it would auto-sort and group. Depending on how long the filter idea would take, this may be faster to implement, but I don't know.

re: inefficient claim -- this window would only be used by a VERY small group of people, and never during an encounter or something like that. I wouldn't mind if it was extremely inefficient, since if I'm browsing the loot history it's because I **need** to know something, and finding that something quickly is extremely important as a loot master.

This doesn't handle how to quickly find tokens for users, though. As someone that loots tokens currently, we use a google docs sheet to track it. I really wish it'd show up in the loot panel somewhere, but that'd probably be harder than having it in the loot history.

**Comment by Raylehnhoff** [comment]
After talking with my raid leader, tokens could be handled in the main loot frame like this:

[Class] Daegan [equippedItem] [X Tokens] [new item]

X Tokens would be hoverable, and would have the count in place of "X". Hovering would show the token quality and slot of the token. This would make it readily available for us to see what tokens they have been looted historically.

This isn't distinctly about the Loot History table, though, and could probably be spun off as another feature request.

**Comment by Eriner** [comment]
I am working on a new History window module that will allow for customizable views and multiple filetype exports of loot (CSV, Json, XML, HTML, etc)
