### ISSUE TITLE
RCLootCouncil "Do you want to use for this raid" doesn't appear until /reload

### ISSUE THREAD

**Issue by Eriner** [Eriner/RCLootCouncil#6]

**Comment by evil-morfar** [comment]
I'm wondering why we aren't seeing loads of complaints about this.

Eitherway, I guess the best way to fix it is to do the check after a 1 sec timer.
Alternatively do the checks on GROUP_ROSTER_UPDATE and store UnitIsGroupLeader() as a variable for use in RAID_INSTANCE_WELCOME.

**Comment by Eriner** [comment]
Yeah, the only problem is the using a timer results in a significant increase in code, and the timers must use OnUpdate() which is cumbersome and not eloquent. I may implement your idea to do the check, as it won't require a funky timer.

**Comment by evil-morfar** [comment]
With AceTimers you could probably do it with like 5 lines :)

**Comment by Eriner** [comment]
Didn't even think about AceTimers! Fix pending!!

**Comment by Eriner** [comment]
Fixed with commit: https://github.com/Eriner/RCLootCouncil/commit/f584d6fbaf20cd64b0f5b13a3ee833c00c9024b9
